name: Ruby

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Install dependent libraries
      run: sudo apt-get install libpq-dev
    - name: bundle app
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Setup Database
      run: |
        cp config/database.yml.github-actions config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
 
    - name: Run RSpec and Cucumber
      run: |
        bundle exec rspec
        bundle exec cucumber
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
