name: Ruby

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        gem install pg -v '0.21.0' --source 'https://rubygems.org/'
        bundle install --jobs 4 --retry 3
        bundle exec rake
